filebeat.prospectors:
- input_type: log
  paths:
    - ${CB_CONTAINER_LOG_PATH}
  tags: ["cb_filebeat"]
  clean_*: 24h

processors:
  - add_cloud_metadata:
  - decode_json_fields:
      fields: ["message"]
      target: ""

output.logstash:
  hosts: '${LOGSTASH_HOSTS}'
  ssl:
    certificate_authorities: ["/etc/ssl/logstash.crt"]

filebeat.inputs:
  scan_frequency: 60s
